name: Scriveqa Cypress Tests

on: [ workflow_dispatch ]

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
        env: 
          CYPRESS_RECORD_KEY: 7a1994c1-69ae-4b88-ac29-e8692508c89e
          
  cypress-run-electron:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          record: true
        env: 
          CYPRESS_RECORD_KEY: 7a1994c1-69ae-4b88-ac29-e8692508c89e
       
  cypress-run-edge:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
          record: true
        env: 
          CYPRESS_RECORD_KEY: 7a1994c1-69ae-4b88-ac29-e8692508c89e
          
